### ISSUE TITLE
Error in Blender 4.0.2

### ISSUE THREAD

**Issue by lajawi** [p2or/blender-batch-import-wavefront-obj#2]
When using this batch importer in Blender 4.0.2, I get this error:
![](https://github.com/p2or/blender-batch-import-wavefront-obj/assets/51792807/50fba7ab-d6b5-4c5b-b97f-9839d479bf66)

**Comment by lajawi** [comment]
It seems like this is natively supported now, I can't find when it was added though.

**Comment by p2or** [comment]
Hi @lajawi,

thanks for your report. Make sure that you are using the appropriate version. Just tested and [version 0.7.0](https://github.com/p2or/blender-batch-import-wavefront-obj?tab=readme-ov-file#versions) works for me as expected in Blender 4+.

> It seems like this is natively supported now, I can't find when it was added though.

Yep, as of 3.5 or something, Blender finally allows to batch import obj's natively (see the [background section](https://github.com/p2or/blender-batch-import-wavefront-obj?tab=readme-ov-file#background)).

Cheers,
Christian

**Comment by lajawi** [comment]
> Just tested and [version 0.7.0](https://github.com/p2or/blender-batch-import-wavefront-obj?tab=readme-ov-file#versions) works for me as expected in Blender 4+.

I hadn't updated it since 0.1.0, but when I encountered the error, I updated to the newest version, in which the error persisted.

**Comment by p2or** [comment]
Hi @lajawi,

the error message cannot be the same because `bpy.ops.import_scene_obj()` (what the error is about) is not called at all in versions above 0.3.0 and has been replaced by [`bpy.ops.wm.obj_import()`](https://github.com/p2or/blender-batch-import-wavefront-obj/blob/Blender-3.5%2B/io_batch_import_objs.py#L144C17-L144C38). Could you please test again and report back to find the issue?

Thanks,
Christian

**Comment by lajawi** [comment]
@p2or, today, I couldn't recreate the issue. I think the issue was that I didn't reload/restart Blender after updating the addon, because now it does work as expected.

**Comment by p2or** [comment]
Thanks for testing, glad it's working fine. Cheers!
